/*
 * To change this template, choose Tool

	    @Override
	    public boolean accept(File f) {
		throw new UnsupportedOperationException("Not supported yet.");
	    }

	    @Override
	    public String getDescription() {
		throw new UnsupportedOperationException("Not supported yet.");
	    }
	} | Templates
 * and open the template in the editor.
 */

/*
 * SaveUpdateFile.java
 *
 * Created on Jul 12, 2010, 7:17:25 PM
 */

package net.smartsocket;

import java.io.File;
import net.smartsocket.updatemanager.ExtensionFileFilter;

/**
 *
 * @author XaeroDegreaz
 */
public class SaveUpdateFile extends javax.swing.JDialog {

    /** Creates new form SaveUpdateFile */
    public SaveUpdateFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        File f = new File("SmartSocket.jar");
        chooser = new javax.swing.JFileChooser(f);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        chooser.setSelectedFile(f);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(net.smartsocket.Main.class).getContext().getResourceMap(SaveUpdateFile.class);
        chooser.setDialogTitle(resourceMap.getString("chooser.dialogTitle")); // NOI18N
        chooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        chooser.setFileFilter(new ExtensionFileFilter("SmartSocket JAR Library", new String[] { "JAR" }));
        chooser.setSelectedFile(new java.io.File("C:\\Program Files (x86)\\NetBeans 6.8\\SmartSocket.jar"));
        chooser.setName("chooser"); // NOI18N
        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_chooserActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveUpdateFile dialog = new SaveUpdateFile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser chooser;
    // End of variables declaration//GEN-END:variables

}
